apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: announcements-ingress
  namespace: announcements
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: anc.dev.addisonserver.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: announcements-service
                port:
                  number: 80
