apiVersion: v1
kind: Service
metadata:
  name: announcements-service
  namespace: announcements
  labels:
    app: announcements
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: announcements
